// -- This file is auto-generated by generate_and_split.py -- //
// -- DO NOT EDIT BY HAND -- //

generate
    genvar i, j;

    for(i = 0; i < NUM_BANKS; i = i + 1) begin: BANK_GEN
        assign bank_select_A[i] = (addr_A[AW-1:AW_BRAM] == i);
        assign bank_select_B[i] = (addr_B[AW-1:AW_BRAM] == i);

        for(j = 0; j < RAM_SLICES; j = j + 1) begin: SLICE_GEN

            if (i == 0 && j == 0) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_0_0.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 0 && j == 1) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_0_1.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 0 && j == 2) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_0_2.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 0 && j == 3) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_0_3.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 1 && j == 0) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_1_0.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 1 && j == 1) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_1_1.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 1 && j == 2) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_1_2.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 1 && j == 3) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_1_3.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 2 && j == 0) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_2_0.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 2 && j == 1) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_2_1.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 2 && j == 2) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_2_2.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 2 && j == 3) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_2_3.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 3 && j == 0) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_3_0.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 3 && j == 1) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_3_1.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 3 && j == 2) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_3_2.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 3 && j == 3) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_3_3.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 4 && j == 0) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_4_0.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 4 && j == 1) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_4_1.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 4 && j == 2) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_4_2.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 4 && j == 3) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_4_3.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 5 && j == 0) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_5_0.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 5 && j == 1) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_5_1.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 5 && j == 2) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_5_2.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 5 && j == 3) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_5_3.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 6 && j == 0) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_6_0.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 6 && j == 1) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_6_1.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 6 && j == 2) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_6_2.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 6 && j == 3) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_6_3.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 7 && j == 0) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_7_0.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 7 && j == 1) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_7_1.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 7 && j == 2) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_7_2.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 7 && j == 3) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_7_3.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 8 && j == 0) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_8_0.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 8 && j == 1) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_8_1.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 8 && j == 2) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_8_2.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 8 && j == 3) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_8_3.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 9 && j == 0) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_9_0.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 9 && j == 1) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_9_1.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 9 && j == 2) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_9_2.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 9 && j == 3) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_9_3.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 10 && j == 0) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_10_0.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 10 && j == 1) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_10_1.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 10 && j == 2) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_10_2.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 10 && j == 3) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_10_3.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 11 && j == 0) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_11_0.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 11 && j == 1) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_11_1.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 11 && j == 2) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_11_2.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 11 && j == 3) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_11_3.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 12 && j == 0) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_12_0.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 12 && j == 1) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_12_1.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 12 && j == 2) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_12_2.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 12 && j == 3) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_12_3.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 13 && j == 0) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_13_0.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 13 && j == 1) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_13_1.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 13 && j == 2) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_13_2.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 13 && j == 3) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_13_3.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 14 && j == 0) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_14_0.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 14 && j == 1) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_14_1.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 14 && j == 2) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_14_2.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 14 && j == 3) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_14_3.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 15 && j == 0) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_15_0.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 15 && j == 1) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_15_1.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 15 && j == 2) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_15_2.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else             if (i == 15 && j == 3) begin
                genram #(
                    .AW(AW_BRAM),
                    .DW(DW_BRAM),
                    .INIT(1),
                    .ROMFILE("fw_15_3.mem")
                )
                RAM_SLICE (
                     .clk_A(clk),
                     .clk_B(clk),
                     .wr_A(bank_select_A[i] & wr_en_A[j]),
                     .wr_B(bank_select_B[i] & wr_en_B[j]),
                     .addr_A(addr_A[AW_BRAM-1:0]),
                     .addr_B(addr_B[AW_BRAM-1:0]),
                     .data_in_A(data_in_A[DW_BRAM*j+:DW_BRAM]),
                     .data_in_B(data_in_B[DW_BRAM*j+:DW_BRAM]),
                     .data_out_A(bank_data_out_A[i][DW_BRAM*j+:DW_BRAM]),
                     .data_out_B(bank_data_out_B[i][DW_BRAM*j+:DW_BRAM])
                );
            end else            begin end

        end // SLICE_GEN
    end // BANK_GEN
endgenerate
